//
//  CreditsTableViewController.m
//  BabyName
//
//  Created by Massimo Peri on 13/11/14.
//  Copyright (c) 2014 Massimo Peri. All rights reserved.
//

#import "CreditsTableViewController.h"

#import "Acknowledgement.h"
#import "LicenseViewController.h"


@interface CreditsTableViewController ()

@property (nonatomic, strong) NSMutableArray *acknowledgements;

@end


@implementation CreditsTableViewController

- (void)viewDidLoad
{
    [super viewDidLoad];

    NSDictionary *root = [NSDictionary dictionaryWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"Acknowledgements"
                                                                                                    ofType:@"plist"]];
    NSMutableArray *acknowledgmentsArray = [NSMutableArray arrayWithArray:root[@"PreferenceSpecifiers"]];
    
    [acknowledgmentsArray removeObjectAtIndex:0];
    [acknowledgmentsArray removeLastObject];

    self.acknowledgements = [[NSMutableArray alloc] init];
    for (NSDictionary *dict in acknowledgmentsArray) {
        Acknowledgement *acknowledgement = [[Acknowledgement alloc] init];
        acknowledgement.name = dict[@"Title"];
        acknowledgement.license = dict[@"FooterText"];
        
        [self.acknowledgements addObject:acknowledgement];
    }
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

 #pragma mark - Navigation
 
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
    if ([[segue identifier] isEqualToString:@"ShowLicenseSegue"]) {
        NSIndexPath *indexPath = [self.tableView indexPathForCell:(UITableViewCell *)sender];
        
        LicenseViewController *viewController = [segue destinationViewController];
        
        Acknowledgement *selectedAcknowledgement = self.acknowledgements[indexPath.row];
        viewController.title = selectedAcknowledgement.name;
        viewController.license = selectedAcknowledgement.license;
    }
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return self.acknowledgements.count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"CreditsCell"
                                                            forIndexPath:indexPath];
    
    cell.textLabel.text = ((Acknowledgement *)self.acknowledgements[indexPath.row]).name;
    
    return cell;
}

- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section
{
    return @"Generated by CocoaPods (cocoapods.org).";
}

@end
